### PR TITLE
Add audit report

### PR DESCRIPTION
**Pull request by chiro-hiro**
Resolve: #1

### CODE REVIEW

**Comment by spape** [comment]
Payout on gitcoin is broken. Reached out to them. Will payout as soon as they've fixed it.

**Comment by spape** [comment]
Just some feedback, maybe you can double check:  
\`\`\`  
require(IERC20(tokenAddress).safeTransfer(payableOwner(), amount), 'Unable to do transaction');  
\`\`\`  
  
safeTransfer is not returning anything, as it has a require within the method itself  
See: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol#L22-L24  
  
so we will just do   
\`\`\`  
SafeERC20(tokenAddress).safeTransfer(payableOwner(), amount);  
\`\`\`  
to mitigate https://github.com/chiro-hiro/ethereum-staking/blob/313aab5a7a2aad0c067d9eec0863cc5cb3f93165/docs/audit.md#H01

**Comment by chiro-hiro** [comment]
@spape My bad, just:

```solidity
SafeERC20(tokenAddress).safeTransfer(payableOwner(), amount);
```

is enough.

**Comment by chiro-hiro** [comment]
To help your contract more secure, I think address check is necessary:

```solidity
    function isContract(address account) internal view returns (bool) {
        // According to EIP-1052, 0x0 is the value returned for not-yet created accounts
        // and 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 is returned
        // for accounts without code, i.e. `keccak256('')`
        bytes32 codehash;
        bytes32 accountHash = 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470;
        // solhint-disable-next-line no-inline-assembly
        assembly { codehash := extcodehash(account) }
        return (codehash != accountHash && codehash != 0x0);
    }
``` 
This code is use [EIP-1052](https://eips.ethereum.org/EIPS/eip-1052). You could implement it as a library.

**Comment by spape** [comment]
```
IERC20(tokenAddress).safeTransfer(payableOwner(), amount);
```

is what I've meant.

**Comment by spape** [comment]
Isn't `isContract` excluding smart contract wallets? We don't wanna exclude those.

**Comment by chiro-hiro** [comment]
I think you need to check, `isContract()` on token's address.

**Comment by spape** [comment]
get it :+1:

**Comment by chiro-hiro** [comment]
989d1b13c897f519b088b34c5a6b3f11caa2e475 looks good,

**Comment by spape** [comment]
Will use isContract from https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol#L26

**Comment by chiro-hiro** [comment]
I'm prefer this code from above since 
https://github.com/vporton/zondirectory/blob/stable/doc/audit.md#m01---possible-wrong-result-in-smart-contract-existence-check

**Comment by spape** [comment]
Makes sense. Thought openzepplin updated this by now :shrug:

**Comment by chiro-hiro** [comment]
May be they do it on other branch, I'm not sure

**Comment by spape** [comment]
btw. tried to reach out per email if you are interested to do more audits with us in the future. Feel free to reach out on Telegram `@SebastianDePay`

**Comment by spape** [comment]
https://github.com/chiro-hiro/ethereum-staking/blob/313aab5a7a2aad0c067d9eec0863cc5cb3f93165/docs/audit.md#m01---possible-wrong-modifier-implement  
  
Yes we want to be able to call `init` multiple times, but only as long as staking hasn't been started yet, hence `block.timestamp < startTime`.   
  
Imagine passing any wrong parameter to init, rewards would be locked for potentially a very long time. So we have time until `startTime` to realize potential problems, and reinitialize the contract if needed.

**Comment by spape** [comment]
https://github.com/chiro-hiro/ethereum-staking/blob/313aab5a7a2aad0c067d9eec0863cc5cb3f93165/docs/audit.md#m03---some-variables-were-not-consumed  
  
This is uniswaps official interface, the `uniswap_v2_pair.sol` is only there to run automated tests, unfortunately uniswap only provides reserve0 via `getReserves()`.

**Comment by spape** [comment]
https://github.com/chiro-hiro/ethereum-staking/blob/313aab5a7a2aad0c067d9eec0863cc5cb3f93165/docs/audit.md#l03---unnecessary-override-modifier

Is actually an open issue with solidity. Because we would like to offer `IDePayLiquidityStaking` as an interface and inherit from our own contract https://github.com/DePayFi/ethereum-staking/blob/fixes-audit-1/contracts/DePayLiquidityStaking.sol#L14 it's currently common practice to flag all the methods from the official interface definition as `override` :shrug:   
  
ethereum/solidity#8281

**Comment by spape** [comment]
All issues (that we considered relevant) addressed/fixed in #4.  
  
Gitcoin payment also worked in the meantime.  
  
Thanks for the collaboration 🙏

**Pull request merged**
